name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Substitua por uma versão específica se necessário

      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt

      - name: Run script
        run: |
          python backend/main.py
        env:
          API_KEY: ${{ secrets.API_KEY }}
